### ISSUE TITLE
Are there any plans to add composer support?

### ISSUE THREAD

**Issue by zachwills** [A5hleyRich/wp-background-processing#13]
I think it would be useful if this were available include in a project via composer. Is this something thats planned?

**Comment by A5hleyRich** [comment]
Yup, it is.

**Comment by zachwills** [comment]
Awesome! That will be great. Any idea as to when it will be?

**Comment by Mte90** [comment]
+1

**Comment by mrror** [comment]
+1

**Comment by A5hleyRich** [comment]
Added

`composer require a5hleyrich/wp-background-processing`

And remember to require the autoloader in your src:

`require_once 'vendor/autoload.php';`
