### ISSUE TITLE
Process data is in the database, but does not get processed

### ISSUE THREAD

**Issue by saten** [A5hleyRich/wp-background-processing#2]
I'm trying to offload a call to wp_mail to a process (tried async request first with no luck)

When I call dispatch() i get an entry like this in wp_options:

wp_wp_mail_batch_666155c47196b967c51a6a3419be51ed (wp_mail is the value of the action in my class)

After that, nothing happens. This holds true even with the sample plugin

**Comment by A5hleyRich** [comment]
Is the site behind basic auth by any chance? If not are you able to xdebug or `error_log` to ensure the background process is actually being hit.

**Comment by saten** [comment]
No basic auth. I see just nothing in error_log about the process, but I’m not even sure what to look for

**Comment by A5hleyRich** [comment]
First you need to determine if your background process is being hit. The easiest way is it `error_log` a value from the `task` method.

https://github.com/A5hleyRich/wp-background-processing-example/blob/master/background-processes/class-example-process.php#L24 

If it's not `error_log`ing the result of `wp_remote_post` may give the reason as to why the HTTP request is failing. 

https://github.com/A5hleyRich/wp-background-processing/blob/master/classes/wp-async-request.php#L58

Can you also check if the health check cron is scheduled?
