### ISSUE TITLE
Proper way to initialize batch

### ISSUE THREAD

**Issue by solepixel** [A5hleyRich/wp-background-processing#4]
In the example, you are using an Admin Menu Bar Link, which has a nonce connected with it and is executed when clicked. When trying to implement this class into a more practical use-case plugin, I'm having a hard time figuring out how to properly feed the queue once every X minutes. I tried an action that occurs on 'plugins_loaded' or 'admin_init' that retrieves all my "items" and loops them and uses "push_to_queue" however what I end up is 100s of "batches" with arrays of my "items", then my computer nearly explodes trying to process them all. I even tried to stop the process by checking for a transient that is set to expire after 30 minutes and if the transient exists, it's supposed to bail.

The processing seems to be working great, however when it processes the queue, since there are 100s of them stored, it just keeps processing the same queue over and over and I'm not sure why it doesn't stop.

Here's basically what I'm doing

	<?php
	add_action( 'admin_init', 'sync' );

	$processor = new Sync_Data();

	function sync() {
		if( get_transient( 'data-sync' ) )
			return;

		global $sync_db, $processor;

		$data = $sync_db->get_data(); // (returns a database resultset of objects with 1 property "id")

		foreach ( $data as $item ) {
			$processor->push_to_queue( $item->id );
		}

		set_transient( 'data-sync', '1', MINUTE_IN_SECONDS * 30 );

		$processor->save()->dispatch();
	}

What am I doing wrong that's causing this to repeat infinitely?

**Comment by solepixel** [comment]
Playing with this a little more, I ended up changing the transient name from `data-sync` to `data_sync` and instead of using `1` as the value, I used `WAIT`. One of these 2 changes caused the transient to show up and stop this from happening over and over.

Please feel free to advise on a better way to handle this process. I have about 50,000 records to sync and not sure how well it will run on `admin_init` loading in these IDs to queue. Right now while I'm testing it, I'm only loading about 100 and it's noticeably slower when the admin loads and it's generating the queue.

**Comment by A5hleyRich** [comment]
@solepixel Not sure exactly what would be causing the infinite loop, but storing that many records in the queue probably isn't a good idea with the current implementation. Using the wp_options table was never an ideal solution, which is why I've started working on a new branch, which creates a separate table. Eventually I would like to extend this to have different queue backends such as Redis.

https://github.com/A5hleyRich/wp-background-processing/tree/jobs-database-table

Are you able to try this new branch? It's still WIP but the pushing and processing is working fine.

**Comment by solepixel** [comment]
@A5hleyRich Ok, so using this new branch, should I still be extending WP_Background_Process and implementing everything else the same way, or do I need to be doing something differently?

**Comment by solepixel** [comment]
Ok, I created the table:

`CREATE TABLE `rpwp_queue` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `action` varchar(255) DEFAULT NULL,
  `data` longtext,
  `created_at` datetime DEFAULT NULL,
  `attempts` bigint(25) DEFAULT NULL,
  `locked` tinyint(1) DEFAULT NULL,
  `locked_at` datetime DEFAULT NULL,
  `available_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16810 DEFAULT CHARSET=latin1;`

I also removed `->save()` from `$this->processor->save()->dispatch()`.

I still had to leave my transient in place to stop the queue creator from running every time admin_init. If this library wasn't designed to use this in this way, I can work on my own method to get the queue populated in intervals and preventing it from compounding on top of itself. Thanks for sharing this branch! I'll let you know if I have any more feedback.

**Comment by solepixel** [comment]
Ok, so I also discovered the worker is being used in the cli-command.php file in the listen method. I assume if I want this automated, I need to add this to a cron?

**Comment by solepixel** [comment]
I think I'm a bit lost with the new setup. You're using CLI to initialize everything and I could never get it setup on my machine (always get a database error, I think related to MAMP). Sorry for my ignorance, but without documentation, I'm not very good at figuring out how this supposed to work. Do you think you could give me a quick run-down on what's going on/what's changed?

**Comment by A5hleyRich** [comment]
Sorry the new branch is a bit of a mess right now, and the documentation hasn't been updated. I've just realised that the example repo hadn't been pushed either, which I've now done:

https://github.com/A5hleyRich/wp-background-processing-example/tree/new-structure

WP-CLI is optional and allows you to fire up additional queue workers if required, but the HTTP worker is enabled out of the box and works the same way as the older branch.

https://github.com/A5hleyRich/wp-background-processing/blob/jobs-database-table/classes/worker/wp-http-worker.php

The new workflow is like so:

1. Extend the [WP_Job](https://github.com/A5hleyRich/wp-background-processing/blob/jobs-database-table/classes/wp-job.php) class.

```
<?php
class WP_Example_Job extends WP_Job {
	/**
	 * @var string
	 */
	protected $param1;

	/**
	 * @var string
	 */
	protected $param2;
	/**
	 * WP_Example_Job constructor.
	 *
	 * @param $name
	 */
	public function __construct( $param1, $param2 ) {
		$this->param1 = $param1;
		$this->param2 = $param2;
	}

	/**
	 * Handle
	 *
	 * Override this method to perform any actions required on each
	 * queue item. Return the modified item for further processing
	 * in the next pass through. Or, return false to remove the
	 * item from the queue.
	 *
	 * @param mixed $item Queue item to iterate over
	 *
	 * @return mixed
	 */
	public function handle() {
		// Process the job
	}
}
```

The only required method is `handle` which performs the queue logic. You can pass optional data to the `__constructor`, which is then available in your handle method for processing.

2. Jobs are pushed to the queue using the helper function `wp_queue`.

```
wp_queue( new WP_Example_Job( $param1, $param2 ) );
```

That's all there is to it. There's no longer any need to dispatch the job as it's taken care of by the HTTP worker. If you're still having issues after trying the steps here, let's arrange to jump on Skype and I'll walk you through it.

**Comment by elvismdev** [comment]
@A5hleyRich is the [jobs-database-table](https://github.com/A5hleyRich/wp-background-processing/tree/jobs-database-table) now stable or good to work with?
