### ISSUE TITLE
Tasks duplicated on a multiple app server environment

### ISSUE THREAD

**Issue by mckernanin** [A5hleyRich/wp-background-processing#40]
I have a site on AWS Elastic Beanstalk, and I've written a custom API integration for Gravity Forms, using their feed addon with background processing enabled. We're seeing an issue where when the site is under significant load, the same background process will get fired off twice (as seen due to duplicate/conflicting info on GF entries). When there are duplicate requests to the API, they come from 2 different IP addresses, so more than one app server is trying to process the task. My background task consists of a API request, that once a response is received writes data onto the entry. 

Let me know what info can help diagnose, and I will provide what I can.

**Comment by delitestudio** [comment]
We're seeing the same issue, multiple duplicated background processes spawned when WP-Cron is enabled. Using a real Cron it seems to spawn a single process every time, even under load.

**Comment by mckernanin** [comment]
Closing this issue, as I'm not working on that project anymore.
