### ISSUE TITLE
dispatch() method never gets called

### ISSUE THREAD

**Issue by Luc45** [A5hleyRich/wp-background-processing#54]
Here's my code:

functions.php or similar:
```
    // Necessary autoloaders here
   // @hooked at plugins_loaded with priority PHP_INT_MAX
    $setup_database = new WP_Async_Setup_Database();
    $setup_database->data( ['user_id' => 17] );
    $setup_database->dispatch();
```

WP_Async_Setup_Database.php:
```
<?php
class WP_Async_Setup_Database extends WP_Async_Request {

    /**
     * @var string
     */
    protected $action = 'setup_database';

    /**
     * Handle
     *
     * Override this method to perform any actions required
     * during the async request.
     */
    protected function handle() {
        // Stuff here that never gets called
        error_log("test", 1, 'myemail.com');
    }

}
```
Var_dumping $setup_database shows it has action, prefix, identifier and everything. The problem is the `dispatch()` method that never gets called. I added `var_dump('test');exit;` to `public funciton dispatch()` in `wp-async-request.php` (and wp-background-process.php) but those never get called... I added the `dispatch()` method to `WP_Async_Setup_Database.php` and it does get called.

**Comment by Luc45** [comment]
It seems to be some kind of conflict with Query Monitor. Renaming `abstract class WP_Async_Request` to `abstract class WP_Async_Request_Giraffe` and extending from it, solves it.

**Comment by Luc45** [comment]
Re-opening this as not it's failing on `check_ajax_referer()` on method `maybe_handle()`... Hard.

**Comment by Luc45** [comment]
Facing another issue, as method `maybe_handle()` never gets called

**Comment by PabloWestphalen** [comment]
Running into the same problem as @Luc45

**Comment by Luc45** [comment]
I don't know what I was doing wrong back then, but I managed to do it now. I have written this super simple plugin that does async code. Just place it as wp-content/plugins/async.php, activate it and access your website with ?async_test, then see the error_log:

```
<?php
/**
* Plugin name: Async Test
*/

add_action('plugins_loaded', function() {
    class BackgroundTest2 extends WP_Background_Process
    {
        protected $action = 'just_testing';
        protected function task( $item ) {
            sleep(1);
            error_log($item);
            return false;
        }
    }
});

class BackgroundTest
{
    public function __construct() {
        add_action('plugins_loaded', function() {
            $this->task = new BackgroundTest2;
            if (isset($_GET['async_test'])) {
                $names = ['name1', 'name2', 'name3', 'name4'];

                foreach ( $names as $name ) {
                    $this->task->push_to_queue( $name );
                }

                $this->task->save()->dispatch();
            }
        });
    }
}
new BackgroundTest;
```

It's a good place to start if you're having trouble making it work.
